root: true
env:
  es2022: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
overrides: []
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - '@typescript-eslint'
rules:
  quotes:
    - error
    - single
  semi:
    - error
    - always
  '@typescript-eslint/no-explicit-any': off
  '@typescript-eslint/ban-ts-comment': 1
  import/no-anonymous-default-export: 0
  no-console: 2
  no-extra-boolean-cast: 0
  